'use client'
import NavBar from './components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from './context/AuthContext'
import Header from './components/Header'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>ADR Backend</title>
        <link rel='icon' href='/favicon.ico'></link>
      </Head>
      
      <body className={inter.className}>
        {/* <AuthContextProvider>
          <NavBar></NavBar>
          {children}
        </AuthContextProvider> */}
        <main className='bg-gray-100 min-h-screen'>
          <Header></Header>
        </main>
       

        </body>
    </html>
  )
}
